### ISSUE TITLE
Unable to use svelte testing library with SMUI

### ISSUE THREAD

**Issue by xrd** [hperrin/svelte-material-ui#110]
Steps to reproduce: 

1. Setup a new svelte project.
1. Add svelte testing library + setup Jest.
1. Create a test, see that is passes.
1. Add SMUI.
1. Modify the test to use a Button from SMUI.
1. Test will fail.

I created a repository here to document this:

https://github.com/xrd/jest-svelte-testing

There are only two commits. This is the diff once I add smui to the project and slightly change the test code to use a SMUI button.

https://github.com/xrd/jest-svelte-testing/commit/90ccf5a2e7e44f654a6c2c26ce181954b0cda750

Pretty straightforward to reproduce. If you are using a regular `<button>` tag, you can click on it using the jest `await fireEvent.click(button)` call.

```
$ yarn test
yarn run v1.19.1
warning package.json: No license field
$ jest src
 PASS  src/__tests__/App.spec.js
  #App
    ✓ clicks on the bread button (23ms)

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        1.266s, estimated 2s
Ran all test suites matching /src/i.
Done in 1.84s.

```

If you add svelte-material-ui you get this: `TypeError: Cannot read property '$$' of undefined`.

Full error is here:

```
$ yarn test
yarn run v1.19.1
warning package.json: No license field
$ jest src
 FAIL  src/__tests__/App.spec.js
  #App
    ✕ clicks on the bread button (36ms)

  ● #App › clicks on the bread button

    TypeError: Cannot read property '$$' of undefined

      10 |     const { getByText } = render(App);
      11 |     const button = getByText('Bread');
    > 12 |     await fireEvent.click(button);
         |                     ^
      13 |     const text = 'Bread was clicked.';
      14 |     expect(getByText(text)).toBeInTheDocument();
      15 |   });

      at bubble (node_modules/svelte/internal/index.js:605:33)
      at Object.<anonymous> (src/__tests__/App.spec.js:12:21)

  ● #App › clicks on the bread button

    TypeError: Cannot read property '$$' of undefined

      10 |     const { getByText } = render(App);
      11 |     const button = getByText('Bread');
    > 12 |     await fireEvent.click(button);
         |                     ^
      13 |     const text = 'Bread was clicked.';
      14 |     expect(getByText(text)).toBeInTheDocument();
      15 |   });

      at bubble (node_modules/svelte/internal/index.js:605:33)
      at Object.<anonymous> (src/__tests__/App.spec.js:12:21)

  ● #App › clicks on the bread button

    Unable to find an element with the text: Bread was clicked.. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.

    <body>
      <div>
         
        <button
          class="
        mdc-button
        
        
        
        
        
        
        
        
        
        
        
        
        
      "
        >
          Bread
        </button>
        
      </div>
    </body>

      12 |     await fireEvent.click(button);
      13 |     const text = 'Bread was clicked.';
    > 14 |     expect(getByText(text)).toBeInTheDocument();
         |            ^
      15 |   });
      16 | });
      17 | 

      at Object.getElementError (node_modules/@testing-library/dom/dist/config.js:34:12)
      at Object.<anonymous> (src/__tests__/App.spec.js:14:12)

  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [TypeError: Cannot read property '$$' of undefined]
        at reportException (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
        at innerInvokeEventListeners (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:332:9)
        at invokeEventListeners (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
        at HTMLButtonElementImpl._dispatch (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
        at HTMLButtonElementImpl.dispatchEvent (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
        at HTMLButtonElement.dispatchEvent (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
        at fireEvent (/home/chrisdawson/Projects/jest-testing/node_modules/@testing-library/dom/dist/events.js:624:18)
        at Function.fireEvent.<computed> [as click] (/home/chrisdawson/Projects/jest-testing/node_modules/@testing-library/dom/dist/events.js:690:36)
        at AsyncFunction.click (/home/chrisdawson/Projects/jest-testing/node_modules/@testing-library/svelte/dist/pure.js:152:38)
        at Object.<anonymous> (/home/chrisdawson/Projects/jest-testing/src/__tests__/App.spec.js:12:21) TypeError: Cannot read property '$$' of undefined
        at bubble (/home/chrisdawson/Projects/jest-testing/node_modules/svelte/internal/index.js:605:33)
        at HTMLButtonElement.forward (/home/chrisdawson/Projects/jest-testing/node_modules/@smui/common/forwardEvents.js:17:5)
        at innerInvokeEventListeners (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:316:27)
        at invokeEventListeners (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
        at HTMLButtonElementImpl._dispatch (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
        at HTMLButtonElementImpl.dispatchEvent (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
        at HTMLButtonElement.dispatchEvent (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
        at fireEvent (/home/chrisdawson/Projects/jest-testing/node_modules/@testing-library/dom/dist/events.js:624:18)
        at Function.fireEvent.<computed> [as click] (/home/chrisdawson/Projects/jest-testing/node_modules/@testing-library/dom/dist/events.js:690:36)
        at AsyncFunction.click (/home/chrisdawson/Projects/jest-testing/node_modules/@testing-library/svelte/dist/pure.js:152:38)
        at Object.<anonymous> (/home/chrisdawson/Projects/jest-testing/src/__tests__/App.spec.js:12:21)
        at Object.asyncJestTest (/home/chrisdawson/Projects/jest-testing/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:100:37)
        at /home/chrisdawson/Projects/jest-testing/node_modules/jest-jasmine2/build/queueRunner.js:43:12
        at new Promise (<anonymous>)
        at mapper (/home/chrisdawson/Projects/jest-testing/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
        at /home/chrisdawson/Projects/jest-testing/node_modules/jest-jasmine2/build/queueRunner.js:73:41
        at processTicksAndRejections (internal/process/task_queues.js:93:5)

  console.error node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Uncaught [TypeError: Cannot read property '$$' of undefined]
        at reportException (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/helpers/runtime-script-errors.js:62:24)
        at innerInvokeEventListeners (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:332:9)
        at invokeEventListeners (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
        at HTMLButtonElementImpl._dispatch (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
        at HTMLButtonElementImpl.dispatchEvent (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
        at HTMLButtonElement.dispatchEvent (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
        at fireEvent (/home/chrisdawson/Projects/jest-testing/node_modules/@testing-library/dom/dist/events.js:624:18)
        at Function.fireEvent.<computed> [as click] (/home/chrisdawson/Projects/jest-testing/node_modules/@testing-library/dom/dist/events.js:690:36)
        at AsyncFunction.click (/home/chrisdawson/Projects/jest-testing/node_modules/@testing-library/svelte/dist/pure.js:152:38)
        at Object.<anonymous> (/home/chrisdawson/Projects/jest-testing/src/__tests__/App.spec.js:12:21) TypeError: Cannot read property '$$' of undefined
        at bubble (/home/chrisdawson/Projects/jest-testing/node_modules/svelte/internal/index.js:605:33)
        at HTMLButtonElement.forward (/home/chrisdawson/Projects/jest-testing/node_modules/@smui/common/forwardEvents.js:17:5)
        at innerInvokeEventListeners (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:316:27)
        at invokeEventListeners (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:267:3)
        at HTMLButtonElementImpl._dispatch (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:214:9)
        at HTMLButtonElementImpl.dispatchEvent (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:87:17)
        at HTMLButtonElement.dispatchEvent (/home/chrisdawson/Projects/jest-testing/node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:144:23)
        at fireEvent (/home/chrisdawson/Projects/jest-testing/node_modules/@testing-library/dom/dist/events.js:624:18)
        at Function.fireEvent.<computed> [as click] (/home/chrisdawson/Projects/jest-testing/node_modules/@testing-library/dom/dist/events.js:690:36)
        at AsyncFunction.click (/home/chrisdawson/Projects/jest-testing/node_modules/@testing-library/svelte/dist/pure.js:152:38)
        at Object.<anonymous> (/home/chrisdawson/Projects/jest-testing/src/__tests__/App.spec.js:12:21)
        at Object.asyncJestTest (/home/chrisdawson/Projects/jest-testing/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:100:37)
        at /home/chrisdawson/Projects/jest-testing/node_modules/jest-jasmine2/build/queueRunner.js:43:12
        at new Promise (<anonymous>)
        at mapper (/home/chrisdawson/Projects/jest-testing/node_modules/jest-jasmine2/build/queueRunner.js:26:19)
        at /home/chrisdawson/Projects/jest-testing/node_modules/jest-jasmine2/build/queueRunner.js:73:41
        at processTicksAndRejections (internal/process/task_queues.js:93:5)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        1.969s
Ran all test suites matching /src/i.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by xrd** [comment]
Additional context: if I debug inside VS code, I see that inside `svelte/internal/index.js` on line 561 there is a call to `set_current_component` several times. The last time it calls it with undefined.

The calls to `set_current_component` get called with these parameters in order:

1. `component: App {}`
1. `component: Button_1 {}`
1. `component: Button {}`
1. `component: Button_1 {$$: Object, $set: , $capture_state: , …}`
1. `component: App {$$: Object, $capture_state: , $inject_state: }`
1. `component: undefined`

Then, it gets into the bubble function on line 605 of `index.js`. And, when it attempts to access `$$` inside `component`, it crashes.

**Comment by darryl-snow** [comment]
@xrd did you ever find a solution to this?

**Comment by xrd** [comment]
@darryl-snow Not yet. I'm open to suggestions on how to troubleshoot. And I'll be in the svelte discord channel later today discussing it if you want to join the conversation.

**Comment by alexstaroselsky** [comment]
Were there solutions identified?

**Comment by xrd** [comment]
@alexstaroselsky No, I never got a good answer. :(

**Comment by grclaeys** [comment]
For anyone who finds this, updating SMUI to the latest version resolved this for me. We were on a beta release, but updating to `1.1.0` fixed it.

**Comment by hperrin** [comment]
Since there is a new release (5.0), and this issue was filed prior to that release and hasn't had any updates in at least six months, I'm going to close it as part of a mass issue clean up. If this issue is still relevant, please re-open it and mention me in a comment, and I will triage the issue into a relevant milestone. Thank you for your patience, and I apologize for any inconvenience.
