### ISSUE TITLE
SMUI not working with Sveltekit

### ISSUE THREAD

**Issue by wnederhof** [hperrin/svelte-material-ui#237]
**Describe the bug**
Unable to use SMUI components with Sveltekit.

```
Must use import to load ES Module: /Users/wouternederhof/projects/<...>/node_modules/@smui/top-app-bar/index.js require() of ES modules is not supported. require() of /Users/wouternederhof/projects/<...>/node_modules/@smui/top-app-bar/index.js from /Users/wouternederhof/projects/<...>/node_modules/vite/dist/node/chunks/dep-994e0558.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules. Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/wouternederhof/projects/<...>/node_modules/@smui/top-app-bar/package.json.

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/wouternederhof/projects/<...>/node_modules/@smui/top-app-bar/index.js
require() of ES modules is not supported.
require() of /Users/wouternederhof/projects/<...>/node_modules/@smui/top-app-bar/index.js from /Users/wouternederhof/projects/<...>/node_modules/vite/dist/node/chunks/dep-994e0558.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/wouternederhof/projects/<...>/node_modules/@smui/top-app-bar/package.json.

    at new NodeError (node:internal/errors:329:5)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1125:13)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at nodeRequire (/Users/wouternederhof/projects/<...>/node_modules/vite/dist/node/chunks/dep-994e0558.js:69077:17)
    at ssrImport (/Users/wouternederhof/projects/<...>/node_modules/vite/dist/node/chunks/dep-994e0558.js:69035:20)
    at eval (/Users/wouternederhof/projects/<...>/src/routes/apps/index.svelte:7:31)
    at instantiateModule (/Users/wouternederhof/projects/<...>/node_modules/vite/dist/node/chunks/dep-994e0558.js:69063:166)
```

**To Reproduce**
Using node 15.6.0, I create a project using `npm init svelte@next my-app` using the `demo` application settings with Typescript. Then I follow the tutorial on `https://github.com/hperrin/svelte-material-ui/blob/master/SVELTEKIT.md`: I add the theme and (in this case) the smui-top-bar. In my code, I write:

```
<script>
    import TopAppBar from '@smui/top-app-bar';
</script>
<TopAppBar variant="static" color="secondary">
</TopAppBar>
```
This will trigger the error.

**Expected behavior**
No error should be thrown and after extending the app bar, it should show on the browser.

**Additional context**
My `package.json`:
```
{
  ...,
  "scripts": {
    "dev": "svelte-kit dev",
    "build": "svelte-kit build",
    "preview": "svelte-kit preview",
    "lint": "prettier --check . && eslint --ignore-path .gitignore .",
    "format": "prettier --write .",
    "prepare": "npm run vite-workaround",
    "vite-workaround": "find node_modules/@material/ -name \"*.js.map\" -type f -delete"
  },
  "devDependencies": {
    "@smui/top-app-bar": "^4.1.0",
    "@sveltejs/kit": "next",
    "@typescript-eslint/eslint-plugin": "^4.19.0",
    "@typescript-eslint/parser": "^4.19.0",
    "eslint": "^7.22.0",
    "eslint-config-prettier": "^8.1.0",
    "eslint-plugin-svelte3": "^3.2.0",
    "prettier": "~2.2.1",
    "prettier-plugin-svelte": "^2.2.0",
    "smui-theme": "^4.1.0",
    "svelte": "^3.34.0",
    "svelte-preprocess": "^4.0.0",
    "tslib": "^2.0.0",
    "typescript": "^4.0.0",
    "vite": "^2.1.0"
  },
  "type": "module",
  "dependencies": {
    "@fontsource/fira-mono": "^4.2.2",
    "@lukeed/uuid": "^2.0.0",
    "cookie": "^0.4.1"
  }
}
```
This also applies on Vite 2.2.3.

**Comment by hperrin** [comment]
This is a known issue with Vite/SvelteKit. Put SMUI packages in your `noExternal` Vite config.

**Comment by hperrin** [comment]
If SvelteKit already puts everything from regular dependencies into noExternal, you can just move them there, but I've heard they don't do that anymore. (Haven't verified.)

**Comment by wnederhof** [comment]
Thank you hperrin. I see that in the examples SMUI used `npm -D` (which is add to devDependencies). When I added this to dependencies instead, it worked without changing the above. Just a question: why do the examples use `npm -D`? SMUI is not meant to be used by the devs only, right?

**Comment by djavorek** [comment]
>  SMUI is not meant to be used by the devs only, right?

I am here with the same question. Why would I need to use SMUI packages as dev deps?

**Comment by NickantX** [comment]
> Thank you hperrin. I see that in the examples SMUI used `npm -D` (which is add to devDependencies). When I added this to dependencies instead, it worked without changing the above. Just a question: why do the examples use `npm -D`? SMUI is not meant to be used by the devs only, right?

No, it is simply convention for Svelte to install components into devDependencies, since svelte is a compiler it's not necessary to install them as runtime dependencies. In reality, it doesn't really matter which you choose, and for some environments it may be better to install SMUI packages as normal dependencies (such as with Cloudflare Pages)
