### ISSUE TITLE
'HelperText' is not exported by node_modules/@smui/textfield/index.js

### ISSUE THREAD

**Issue by ramaisen** [hperrin/svelte-material-ui#24]
Hi,
I want to write a ChipInput component to add to the library but i cant get the examples to work
im using Rollup with these conf

`import svelte from 'rollup-plugin-svelte';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';

//import includePaths from 'rollup-plugin-includepaths';
import sass from 'rollup-plugin-sass';
import scss from 'rollup-plugin-scss';

const production = !process.env.ROLLUP_WATCH;

export default {
	input: 'src/main.js',
	output: {
		sourcemap: true,
		format: 'iife',
		name: 'app',
		file: 'public/bundle.js'
	},
	plugins: [
		
		svelte({
			// enable run-time checks when not in production
			dev: !production,
			// we'll extract any component CSS out into
			// a separate file — better for performance
			css: css => {
				css.write('public/bundle.css');
			},
		}),

		sass(),
		scss(),

		// If you have external dependencies installed from
		// npm, you'll most likely need these plugins. In
		// some cases you'll need additional configuration —
		// consult the documentation for details:
		// https://github.com/rollup/rollup-plugin-commonjs
		resolve({
			browser: true,
			dedupe: importee => importee === 'svelte' || importee.startsWith('svelte/')
		}),

		commonjs(),

		// Watch the `public` directory and refresh the
		// browser on changes when not in production
		!production && livereload('public'),

		// If we're building for production (npm run build
		// instead of npm run dev), minify
		production && terser()
	],
	watch: {
		clearScreen: false
	}
};
`

and i get this error
`18: <script>
19:   import Button from '@smui/button';
20:   import Fab from '@smui/fab';
                       ^
21:   import Textfield, {HelperText} from '@smui/textfield';
22:   import {Label, Icon} from '@smui/common';
Error: 'HelperText' is not exported by node_modules/@smui/textfield/index.js
    at error (/home/ramiro/Escritorio/Dev/svelte-material-ci/node_modules/rollup/dist/rollup.js:9419:30)
    at Module.error (/home/ramiro/Escritorio/Dev/svelte-material-ci/node_modules/rollup/dist/rollup.js:13402:9)
    at handleMissingExport (/home/ramiro/Escritorio/Dev/svelte-material-ci/node_modules/rollup/dist/rollup.js:13322:21)
    at Module.traceVariable (/home/ramiro/Escritorio/Dev/svelte-material-ci/node_modules/rollup/dist/rollup.js:13711:17)
    at ModuleScope.findVariable (/home/ramiro/Escritorio/Dev/svelte-material-ci/node_modules/rollup/dist/rollup.js:12414:39)
    at FunctionScope.findVariable (/home/ramiro/Escritorio/Dev/svelte-material-ci/node_modules/rollup/dist/rollup.js:2981:38)
    at ChildScope.findVariable (/home/ramiro/Escritorio/Dev/svelte-material-ci/node_modules/rollup/dist/rollup.js:2981:38)
    at Identifier$1.bind (/home/ramiro/Escritorio/Dev/svelte-material-ci/node_modules/rollup/dist/rollup.js:8340:40)
    at NewExpression.bind (/home/ramiro/Escritorio/Dev/svelte-material-ci/node_modules/rollup/dist/rollup.js:7969:23)
    at NewExpression.bind (/home/ramiro/Escritorio/Dev/svelte-material-ci/node_modules/rollup/dist/rollup.js:11760:15)`

Do you have an idea of why?
Thank you!
do you have a

**Comment by hperrin** [comment]
Hey @ramaisen, I've included the helper text in a different file, so that if you don't import it, you don't get all the extra css for it. You can import it from `@smui/textfield/helper-text`. Soon I'll have the documentation done to clear this up. :)

**Comment by hperrin** [comment]
(it's the default export)
