### ISSUE TITLE
Doesn't build.

### ISSUE THREAD

**Issue by geoidesic** [hperrin/svelte-material-ui#256]
**Describe the bug**
ENOENT: no such file or directory, open '/Users/repo/GitHub/peakVTT/node_modules/@material/dom/index.ts'
Error: ENOENT: no such file or directory, open '/Users/repo/GitHub/peakVTT/node_modules/@material/dom/index.ts'

**To Reproduce**
1. Follow the Sveltekit installation instructions
2. Try `npm run dev`
3. See error

**Expected behavior**
It should not error.

**Desktop (please complete the following information):**
 - OS: Mac OS X 10.15.7
 - Browser chrome
 - Version 91.0.4472.77 (Official Build) (x86_64)

**Comment by hperrin** [comment]
Hmm. We're there any errors reported during the vite-workaround script?

**Comment by geoidesic** [comment]
I don't really understand the whole vite-workaround script thing. The installation instructions said to add the script (but didn't say to where, I assume to package.json) but it didn't say what to do with the script. I didn't do anything with the scripts that were added, as there were no instructions about that.

**Comment by geoidesic** [comment]
There are also typos in the docs. The scripts shown are not valid JSON.

**Comment by geoidesic** [comment]
I see you fixed the invalid JSON. I tried running `npm run prepare` now and I get this error:
```
Compiling SMUI Styles...
/Users/noeldacosta/repo/GitHub/peakVTT/node_modules/yargs/build/index.cjs:2772
                throw err;
                ^

Error: Module loop: this module is already being loaded.
  ╷
1 │ @use 'smui-theme';
  │ ^^^^^^^^^^^^^^^^^
  ╵
  node_modules/smui-theme/_index.scss 1:1  root stylesheet
    at Object._newRenderError (/Users/noeldacosta/repo/GitHub/peakVTT/node_modules/sass/sass.dart.js:13190:19)
    at Object._wrapException (/Users/noeldacosta/repo/GitHub/peakVTT/node_modules/sass/sass.dart.js:13018:16)
    at StaticClosure._renderSync (/Users/noeldacosta/repo/GitHub/peakVTT/node_modules/sass/sass.dart.js:12996:18)
    at Object.Primitives_applyFunction (/Users/noeldacosta/repo/GitHub/peakVTT/node_modules/sass/sass.dart.js:1130:30)
    at Object.Function_apply (/Users/noeldacosta/repo/GitHub/peakVTT/node_modules/sass/sass.dart.js:5897:16)
    at _callDartFunctionFast (/Users/noeldacosta/repo/GitHub/peakVTT/node_modules/sass/sass.dart.js:7599:16)
    at Object.renderSync (/Users/noeldacosta/repo/GitHub/peakVTT/node_modules/sass/sass.dart.js:7577:18)
    at Object.handler (/Users/noeldacosta/repo/GitHub/peakVTT/node_modules/smui-theme/bin/index.js:50:27)
    at Object.runCommand (/Users/noeldacosta/repo/GitHub/peakVTT/node_modules/yargs/build/index.cjs:446:48)
    at Object.parseArgs [as _parseArgs] (/Users/noeldacosta/repo/GitHub/peakVTT/node_modules/yargs/build/index.cjs:2697:57) {
  formatted: 'Error: Module loop: this module is already being loaded.\n' +
    '  ╷\n' +
    "1 │ @use 'smui-theme';\n" +
    '  │ ^^^^^^^^^^^^^^^^^\n' +
    '  ╵\n' +
    '  node_modules/smui-theme/_index.scss 1:1  root stylesheet',
  line: 1,
  column: 1,
  file: '/Users/noeldacosta/repo/GitHub/peakVTT/node_modules/smui-theme/_index.scss',
  ```

**Comment by GiorgosK** [comment]
Fixed invalid json in package.json replacing double quote " with single quote ' 
```
    "prepare": "npm run vite-workaround",
    "vite-workaround": "find node_modules/@material/ -name '*.js.map' -type f -delete"   
```
After running `npm run prepare` things are working as expected but 
I see a lot of compilation warnings similar to this  
```
9:01:28 PM [vite] Failed to load source map for /node_modules/@material/ripple/types.js?v=6b2320ea.
```

**Comment by luxee** [comment]
I have the same problem for:
- MacOS X 10.15.7
- NodeJS 14.17.0
- SvelteKit, installed with ```npm init svelte@next``` command.
  No matter  if Typescript is enabled or not

The result of ```svelte-kit dev``` run:
```
[vite] Error when evaluating SSR module /Users/bugsbunny/prj/study/explain-svelte/src/routes/app/__layout.reset.svelte:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/bugsbunny/prj/study/explain-svelte/node_modules/@smui/top-app-bar/index.js
require() of ES modules is not supported.
require() of /Users/bugsbunny/prj/study/explain-svelte/node_modules/@smui/top-app-bar/index.js from /Users/bugsbunny/prj/study/explain-svelte/node_modules/vite/dist/node/chunks/dep-bc228bbb.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/bugsbunny/prj/study/explain-svelte/node_modules/@smui/top-app-bar/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1085:13)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at nodeRequire (/Users/bugsbunny/prj/study/explain-svelte/node_modules/vite/dist/node/chunks/dep-bc228bbb.js:68707:17)
    at ssrImport (/Users/bugsbunny/prj/study/explain-svelte/node_modules/vite/dist/node/chunks/dep-bc228bbb.js:68660:20)
    at eval (/Users/bugsbunny/prj/study/explain-svelte/src/routes/app/__layout.reset.svelte:7:31)
    at instantiateModule (/Users/bugsbunny/prj/study/explain-svelte/node_modules/vite/dist/node/chunks/dep-bc228bbb.js:68693:166)
```

package.json:
```
{
  "type": "module",
  ...
}
```

src/routes/app/__layout.reset.svelte:

```
<script>
  import TopAppBar, { Row, Section, Title } from "@smui/top-app-bar"
</script>

<svelte:head>
  <title>App</title>
  <link rel="stylesheet" href="../../node_modules/svelte-material-ui/bare.css" />
</svelte:head>

<TopAppBar>
  <Row>
    <Section>
      <Title>App Prototype</Title>
    </Section>
  </Row>
</TopAppBar>
<slot/>
```

**Comment by johannesrave** [comment]
> 
> 
> I see you fixed the invalid JSON. I tried running `npm run prepare` now and I get this error:
> 
> ```
> Compiling SMUI Styles...
> /Users/repo/GitHub/peakVTT/node_modules/yargs/build/index.cjs:2772
>                 throw err;
>                 ^
> 
> Error: Module loop: this module is already being loaded.
>   ╷
> 1 │ @use 'smui-theme';
>   │ ^^^^^^^^^^^^^^^^^
>   ╵
>   node_modules/smui-theme/_index.scss 1:1  root stylesheet
>     at Object._newRenderError (/Users/repo/GitHub/peakVTT/node_modules/sass/sass.dart.js:13190:19)
>     at Object._wrapException (/Users/repo/GitHub/peakVTT/node_modules/sass/sass.dart.js:13018:16)
>     at StaticClosure._renderSync (/Users/repo/GitHub/peakVTT/node_modules/sass/sass.dart.js:12996:18)
>     at Object.Primitives_applyFunction (/Users/repo/GitHub/peakVTT/node_modules/sass/sass.dart.js:1130:30)
>     at Object.Function_apply (/Users/repo/GitHub/peakVTT/node_modules/sass/sass.dart.js:5897:16)
>     at _callDartFunctionFast (/Users/repo/GitHub/peakVTT/node_modules/sass/sass.dart.js:7599:16)
>     at Object.renderSync (/Users/repo/GitHub/peakVTT/node_modules/sass/sass.dart.js:7577:18)
>     at Object.handler (/Users/noeldacosta/repo/GitHub/peakVTT/node_modules/smui-theme/bin/index.js:50:27)
>     at Object.runCommand (/Users/repo/GitHub/peakVTT/node_modules/yargs/build/index.cjs:446:48)
>     at Object.parseArgs [as _parseArgs] (/Users/repo/GitHub/peakVTT/node_modules/yargs/build/index.cjs:2697:57) {
>   formatted: 'Error: Module loop: this module is already being loaded.\n' +
>     '  ╷\n' +
>     "1 │ @use 'smui-theme';\n" +
>     '  │ ^^^^^^^^^^^^^^^^^\n' +
>     '  ╵\n' +
>     '  node_modules/smui-theme/_index.scss 1:1  root stylesheet',
>   line: 1,
>   column: 1,
>   file: '/Users/repo/GitHub/peakVTT/node_modules/smui-theme/_index.scss',
> ```

I have that same error on
- Windows 10
- svelte-kit installed via `npm init svelte@next my-app`
- set up prepare script in _helper and package.json
- the error happens when running prepare or either of these two scripts alone:
    "smui-theme-light": "smui-theme compile static/smui.css -i src/theme"
    "smui-theme-dark": "smui-theme compile static/smui-dark.css -i src/theme/dark"
    so vite-workaround alone seems to be going through
    
When just I try to run the svelte dev-server I get 
    
09:48:44 [vite] new dependencies found: @smui/list, updating...
09:48:46 [vite] ✨ dependencies updated, reloading page...
09:48:46 [vite] Error when evaluating SSR module /node_modules/@smui/ripple/Ripple.js:
TypeError: Cannot read property 'events' of null
    at eval (/node_modules/@smui/ripple/Ripple.js:9:48)
    at instantiateModule (D:\*MY-FILESYSTEM*\smui-test\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:68693:166)
Cannot read property 'events' of null
TypeError: Cannot read property 'events' of null
    at eval (/node_modules/@smui/ripple/Ripple.js:9:48)
    at instantiateModule (D:\*MY-FILESYSTEM*\smui-test\node_modules\vite\dist\node\chunks\dep-bc228bbb.js:68693:166)

**Comment by ewagoner** [comment]
I'm hitting this same thing. Is this library just fundamentally incompatible with Vite at the moment?

**Comment by geoidesic** [comment]
@ewagoner Pretty much. I went with carbon instead.

**Comment by ewagoner** [comment]
I ended up doing the same last night.

**Comment by jquesada2016** [comment]
I'm running into the issue mentioned above. After fixing the workaround JSON syntax error around the quotes, I get the following error:

```
smui-theme compile static/smui.css -i src/theme

Compiling SMUI Styles...
/mnt/c/Dev/Commercial/Importadora Queara/system/app-web-desktop/node_modules/yargs/build/index.cjs:2772
                throw err;
                ^

Error: Module loop: this module is already being loaded.     
  ╷
1 │ @use 'smui-theme';
  │ ^^^^^^^^^^^^^^^^^
  ╵
  node_modules/smui-theme/_index.scss 1:1  root stylesheet   
    at Object._newRenderError (/mnt/c/Dev/Commercial/Importadora Queara/system/app-web-desktop/node_modules/sass/sass.dart.js:13231:19)
    at Object._wrapException (/mnt/c/Dev/Commercial/Importadora Queara/system/app-web-desktop/node_modules/sass/sass.dart.js:13059:16)
    at StaticClosure._renderSync (/mnt/c/Dev/Commercial/Importadora Queara/system/app-web-desktop/node_modules/sass/sass.dart.js:13037:18)
    at Object.Primitives_applyFunction (/mnt/c/Dev/Commercial/Importadora Queara/system/app-web-desktop/node_modules/sass/sass.dart.js:1136:30)
    at Object.Function_apply (/mnt/c/Dev/Commercial/Importadora Queara/system/app-web-desktop/node_modules/sass/sass.dart.js:5903:16)
    at _callDartFunctionFast (/mnt/c/Dev/Commercial/Importadora Queara/system/app-web-desktop/node_modules/sass/sass.dart.js:7605:16)
    at Object.renderSync (/mnt/c/Dev/Commercial/Importadora Queara/system/app-web-desktop/node_modules/sass/sass.dart.js:7583:18)
    at Object.handler (/mnt/c/Dev/Commercial/Importadora Queara/system/app-web-desktop/node_modules/smui-theme/bin/index.js:50:27)
    at Object.runCommand (/mnt/c/Dev/Commercial/Importadora Queara/system/app-web-desktop/node_modules/yargs/build/index.cjs:446:48)
    at Object.parseArgs [as _parseArgs] (/mnt/c/Dev/Commercial/Importadora Queara/system/app-web-desktop/node_modules/yargs/build/index.cjs:2697:57) {
  formatted: 'Error: Module loop: this module is already being loaded.\n' +
    '  ╷\n' +
    "1 │ @use 'smui-theme';\n" +
    '  │ ^^^^^^^^^^^^^^^^^\n' +
    '  ╵\n' +
    '  node_modules/smui-theme/_index.scss 1:1  root stylesheet',
  line: 1,
  column: 1,
  file: '/mnt/c/Dev/Commercial/Importadora Queara/system/app-web-desktop/node_modules/smui-theme/_index.scss',
  status: 1
}
```

**Comment by huyffs** [comment]
Missing theme files caused the problem for me.

https://github.com/hperrin/svelte-material-ui/tree/master/site/src/theme

Copying them to my project solved it.

**Comment by hperrin** [comment]
> I'm hitting this same thing. Is this library just fundamentally incompatible with Vite at the moment?

The demo site uses Vite.

**Comment by jwsinner** [comment]
I was getting the same errors as @jquesada2016 because I forgot the `npx smui-theme template src/theme` command before running `npm run prepare`.

**Comment by risalfajar** [comment]
I have the same issue with @georgenicoll : `undefined mixin`

Had to look at my git history to find the last version that's working. Using these versions works for me:
```json
"devDependencies": {
  "smui-theme": "^5.0.0",
  "@material/theme": "^11.0.0",
  "@smui/button": "^6.0.0-beta.16",
  "@smui/(other components)": "^6.0.0-beta.16",
}

"dependencies": {
  "svelte-material-ui": "^4.2.0",
}
```

**Comment by ahmadshiddiqn** [comment]
> I was getting the same errors as @jquesada2016 @johannesrave because I forgot the `npx smui-theme template src/theme` command before running `npm run prepare`.

This solved my problem of "Error: Module loop: this module is already being loaded.".

I thought that process was optional because it says "Create **your theme files** with `smui-theme`", and I thought "no, I don't want to create my own theme files, I want to use SMUI theme files", that's why I skipped it 😅. My first language is not English, so I think that's my problem that can't understand it properly. But I do think the instruction steps can be clearer like maybe add a step number instead of just using line break for each step

**Comment by MintyMods** [comment]
> Missing theme files caused the problem for me.
> 
> https://github.com/hperrin/svelte-material-ui/tree/master/site/src/theme
> 
> **Copying them to my project solved it.**

Your comment made me double check and sure enough the dark theme was missing (It was there because I edited it about an hour before but now...) anyway sticking it back fixed the issue for me.

Thanks for the heads-up

**Comment by phillipluther** [comment]
I was hitting this issue when `npx smui-theme template`'ing into a directory other than `src/theme`.  To fix it, I made sure `npm run prepare` was looking in the right place.

My theme files were in `src/lib/styles/theme`, so in `package.json` I updated the prepare script like this:

```json
...
"npm run prepare": "npm run smui-theme compile static/smui.css src/lib/styles/theme"
```

That `npm run prepare` kicks off `npm run smui-theme`, which defaults to the `smui-theme compile` command. 

In checking the [`smui-theme` docs](https://www.npmjs.com/package/smui-theme) I saw that its `compile` command takes arguments -- you can tell it where to build to and from. Compile's default src directory is `src/theme`; my prepared light and dark theme files were not in `src/theme`. Not sure _why_ not finding the theme files results in a module loop error … but hitting it seems to track with the many mentions of missing theme files or failures to run `npx smui-theme template src/theme` above.

`smui-theme compile`, by way of `npm-run-prepare`, needs to know where the theme's source files are. If it doesn't find 'em you hit the module loop error.

Old thread, but still open. Posting for posterity!

**Comment by hperrin** [comment]
That is a very odd message for that issue. Maybe I can check for that error and give a hint to check for the theme file.

**Comment by dmgarland** [comment]
Perhaps we might also rename this issue. I found this by accident searching by through the issue list but renaming the theme stylesheet filename fixed my issue.
