### ISSUE TITLE
Wrong _index.scss path in button/styled.ts (line 1: '../' ==> './')

### ISSUE THREAD

**Issue by mellanslag-de** [hperrin/svelte-material-ui#327]
**Describe the bug**
When I want to use the button component in svelte, i get the following error when trying to build the project:
`[!] Error: Could not resolve '../_index.scss' from node_modules\@smui\button\styled.js
Error: Could not resolve '../_index.scss' from node_modules\@smui\button\styled.js
    at error (C:\Users\<user>\<projectFolder>\node_modules\rollup\dist\shared\rollup.js:151:30)
    at ModuleLoader.handleResolveId (C:\Users\<user>\<projectFolder>\node_modules\rollup\dist\shared\rollup.js:19862:24)
    at C:\Users\ddeut\WebstormProjects\my-svelte-project-material3\node_modules\rollup\dist\shared\rollup.js:19856:26`

**To Reproduce**
1. Add `import Button, {Label} from '@smui/button/styled';` to any component.
2. Add `<Button>
		<Label>
			Hello World
		</Label>
	</Button>` to that same component.
3. type `rollup -c` into the terminal
4. Output of above desription occurrs

**Expected behavior**
no error output and the scss file is found

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [not relevant, happens at build time]
 - Version [not relevant, happens at build time]

**Smartphone (please complete the following information):**

**Additional context**
Started just today getting into svelte-material-ui, so please forgive if i missed anything obvious, but to me it seems quite clear that the _index.scss file is simply in the same folder. not the parent folder (so there is one . too much).

Also edited the file locally and then it worked.

node_modules\@smui\button\styled.ts: I change line 1 from `import '../_index.scss';` to `import './_index.scss';`

**Comment by mellanslag-de** [comment]
@hperrin I saw you [corrected it yesterday](https://github.com/hperrin/svelte-material-ui/commit/126d7646fd8ad5048a2bbad94eb0d921d5aef957). Thanks a lot for the quick fix, I'll close this issue now
