### ISSUE TITLE
Sveltekit: require() of ES modules is not supported when building with TopAppBar

### ISSUE THREAD

**Issue by Exomnius** [hperrin/svelte-material-ui#369]
**Describe the bug**
When adding the TopAppBar to the example project (and other project too), the following error ocurs when running `npm run dev`.
```
12:15:05 PM [vite] Error when evaluating SSR module /src/routes/__layout.svelte:
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/***/dev/smui-example-sveltekit/node_modules/@smui/top-app-bar/index.js
require() of ES modules is not supported.
require() of /Users/***/dev/smui-example-sveltekit/node_modules/@smui/top-app-bar/index.js from /Users/***/dev/smui-example-sveltekit/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/***/dev/smui-example-sveltekit/node_modules/@smui/top-app-bar/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at nodeRequire (/Users/***/dev/smui-example-sveltekit/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66559:17)
    at ssrImport (/Users/***/dev/smui-example-sveltekit/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66501:20)
    at eval (/src/routes/__layout.svelte:10:37)
    at async instantiateModule (/Users/***/dev/smui-example-sveltekit/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:66544:9)
Must use import to load ES Module: /Users/***/dev/smui-example-sveltekit/node_modules/@smui/top-app-bar/index.js
require() of ES modules is not supported.
require() of /Users/***/dev/smui-example-sveltekit/node_modules/@smui/top-app-bar/index.js from /Users/***/dev/smui-example-sveltekit/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/***/dev/smui-example-sveltekit/node_modules/@smui/top-app-bar/package.json.
```
The svelte layout component: 
```
<script lang="ts">
	import Button, { Label } from '@smui/button';
    import TopAppBar, { Row, Section, Title as TopAppBarTitle } from '@smui/top-app-bar';
    import IconButton from '@smui/icon-button';

    let lightTheme =
		typeof window === 'undefined' || window.matchMedia('(prefers-color-scheme: light)').matches;
	function switchTheme() {
		lightTheme = !lightTheme;
		let themeLink = document.head.querySelector<HTMLLinkElement>('#theme');
		if (!themeLink) {
			themeLink = document.createElement('link');
			themeLink.rel = 'stylesheet';
			themeLink.id = 'theme';
		}
		themeLink.href = `/smui${lightTheme ? '' : '-dark'}.css`;
		document.head
			.querySelector<HTMLLinkElement>('link[href="/smui-dark.css"]')
			?.insertAdjacentElement('afterend', themeLink);
	}
</script>

<div style="display: flex; justify-content: space-between;">
	<TopAppBar
			variant="static"
	>
		<Row>
			<Section>
				<IconButton class="material-icons">menu</IconButton>
				<TopAppBarTitle>Static</TopAppBarTitle>
			</Section>
			<Section align="end" toolbar>
				<IconButton class="material-icons" aria-label="Download"
				>file_download
				</IconButton
				>
				<IconButton class="material-icons" aria-label="Print this page"
				>print
				</IconButton
				>
				<IconButton class="material-icons" aria-label="Bookmark this page"
				>bookmark
				</IconButton
				>
			</Section>
		</Row>
	</TopAppBar>
	<div class="container"><slot /></div>
	<div class="container">
		<Button on:click={switchTheme}>
			<Label>{lightTheme ? 'Lights off' : 'Lights on'}</Label>
		</Button>
	</div>
</div>

```

**To Reproduce**
1. Checkout `https://github.com/hperrin/smui-example-sveltekit`
2. run `npm i -D @smui/top-app-bar`
3. run `npm i`
4. update the code in the layout so it matches the above code block. 
5. run `npm run dev`
6. Observe the console

**Expected behavior**
No console error and TopAppBar component should work correctly.

**Desktop (please complete the following information):**
 - OS: OSX 10.15.7
 - Sveltekit: 1.0.0-next.196
 - Svelte-material-ui: 6.0.0-beta.2
 - Svelte: 3.44.1
 - Svelte-preprocessor: 4.9.8
 - Node: 14.16.0
 - NPM: 6.14.11

**Solutions I tried**
- Moving SMUI dependencies from `devDependencies` to `dependencies` in the package.json
- Excluding the SMUI dependenvies in the vite config using `ssr.noExternal`

**Comment by Egnus** [comment]
In my project I set `ssr.noExternal` for all the `@smui/packages` and I managed to skip those errors from the `6.0.0-beta.2`

But I hope there will be another solution so the builds and the SSR can run faster with externalisation.

**Comment by Exomnius** [comment]
Did you also use the top-app-bar? Can you post your config/component/package.json/node versions?

**Comment by hperrin** [comment]
This is kinda ridiculous, because there is no `require` in that file.

https://cdn.jsdelivr.net/npm/@smui/top-app-bar@6.0.0-beta.2/index.js

**Comment by hperrin** [comment]
I think Vite is not checking whether it's a module. (It lists that it is in the package.json.)

**Comment by hperrin** [comment]
This should be fixed with the latest release.
