### ISSUE TITLE
TypeError: selected.push is not a function at selectSegment

### ISSUE THREAD

**Issue by michaelcuneo** [hperrin/svelte-material-ui#473]
**Describe the bug**
TypeError: selected.push is not a function at selectSegment

```
SegmentedButton.svelte? [sm]:156 Uncaught TypeError: selected.push is not a function
    at selectSegment (SegmentedButton.svelte? [sm]:156:22)
    at Object.notifySelectedChange (SegmentedButton.svelte? [sm]:106:17)
    at MDCSegmentedButtonFoundation.handleSelected (foundation.ts:108:18)
    at HTMLDivElement.selected_handler (SegmentedButton.svelte? [sm]:13:48)
    at dispatch (dispatch.ts:14:14)
    at Object.notifySelectedChange (Segment.svelte? [sm]:93:13)
    at MDCSegmentedButtonSegmentFoundation.handleClick (foundation.ts:99:18)
    at HTMLButtonElement.click_handler (Segment.svelte? [sm]:30:14)
```

**To Reproduce**
Use SegmentedButton in my project.

**Expected behavior**
No error

**Comment by hperrin** [comment]
Thank you for filing this issue!

I'm going to close this issue for two reasons:

1. v9 has just been released, and I'm going to close all previous issues to be revalidated against v9.
2. SMUI is about to be migrated to the [SciActive Forge](https://forge.sciactive.com/sciactive).

**If you feel this issue should be reopened, please validate that it still applies to the newest version of SMUI (v9), then reopen it.**

As part of the migration to SciActive Forge, this repo **will remain** on GitHub as a mirror, but certain GitHub features will be disabled. This might include GitHub Issues, and I'd like to clean up all of the existing issues to make sure only issues that still apply to v9 get migrated. Thank you so much for your participation!
