### ISSUE TITLE
fix missing-exports-condition

### ISSUE THREAD

**Issue by ruckc** [hperrin/svelte-material-ui#644]
**Describe the bug**
It appears that at somepoint sveltekit changed to use package.json's `exports` field instead of `svelte` as the preferred behavior.

**To Reproduce**
1. `npm create svelete@latest`
2. `npm add @smui/button`
3. `npm run dev`

**Expected behavior**
@smui components to work without warning.

**Screenshots**
![image](https://github.com/hperrin/svelte-material-ui/assets/1426401/e4c87be7-f9e7-446b-a0bc-84cc3d43a5ca)

**Additional context**
https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition

**Comment by ludovic-trubert** [comment]
When I migrated my SvelteKit app from version 1 to 2, I had this warning too and my app did not build anymore. I had the error : 
```
> Using @sveltejs/adapter-node
error during build:
RollupError: Expression expected
    at getRollupEror (file:///.../website-app/node_modules/rollup/dist/es/shared/parseAst.js:375:41)
    at ParseError.initialise (file:///.../website-app/node_modules/rollup/dist/es/shared/node-entry.js:11155:28)
    at convertNode (file:///.../website-app/node_modules/rollup/dist/es/shared/node-entry.js:12895:10)
    at convertProgram (file:///.../website-app/node_modules/rollup/dist/es/shared/node-entry.js:12215:12)
    at Module.setSource (file:///.../website-app/node_modules/rollup/dist/es/shared/node-entry.js:14039:24)
    at async ModuleLoader.addModuleSource (file:///.../website-app/node_modules/rollup/dist/es/shared/node-entry.js:18697:13)
```
When I debug the build, this error occurs when parsing the SMUI components Card and Slider. Components I use in my app.

 If I add the export like describe by @ruckc in these 2 components package.json, I still have some warning on other components, but the application build and run correctly :
 
 ```
"exports": {
  ".": {
    "svelte": "./dist/index.js"
  }
}
```

**Comment by jerch** [comment]
Created PR #649, which fixes this issue for the demo site.

**Comment by hperrin** [comment]
Thanks @jerch for the PR. Let me know if the fix causes any issues. I also added the `package.json` export. I'll release a new version as soon as I add a note in the docs for this.
