### ISSUE TITLE
Error: Could not resolve './Label' from node_modules/svelte-material-ui/components/common/index.js

### ISSUE THREAD

**Issue by caschbre** [hperrin/svelte-material-ui#7]
I created a new svelte project using [this svelte template](https://github.com/YogliB/svelte-component-template) that uses rollup.  I npm installed the svelte-material-ui package and then dropped the demo content from the README into App.svelte.  When I do "npm run dev" I get the following error...

```
[!] Error: Could not resolve './Label' from node_modules/svelte-material-ui/components/common/index.js
Error: Could not resolve './Label' from node_modules/svelte-material-ui/components/common/index.js
    at error (/svelte-mui-demo/node_modules/rollup/dist/rollup.js:9421:30)
    at ModuleLoader.handleMissingImports (/svelte-mui-demo/node_modules/rollup/dist/rollup.js:16456:17)
    at ModuleLoader.<anonymous> (/svelte-mui-demo/node_modules/rollup/dist/rollup.js:16507:26)
    at Generator.next (<anonymous>)
    at fulfilled (/svelte-mui-demo/node_modules/rollup/dist/rollup.js:15480:28)
```

With this one I'm running v1.0.0-alpha.8.

**Comment by hperrin** [comment]
It looks like you don't have your bundler set up to look for 'svelte' extension files by default. Today, I added all the extensions to the imports, so you shouldn't see this error with the latest version.
